#!/usr/bin/env python3
"""Generate PV1-02 P2 manuscript tables from committed HGFX evidence.

The generator intentionally uses only repository evidence. It fails if a required
input, evidence ID, or provenance field is absent, and it preserves historical
FAIL / REFERENCE_LIMITATION_MATCH classifications verbatim.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any, Iterable


TABLE_NAMES = (
    "model_workflow_coverage.md",
    "official_matlab_demo_parity.md",
    "fitting_statistics_classification.md",
    "recovery_model_selection.md",
    "backend_gpu_applicability.md",
    "release_reproducibility_provenance.md",
)

REQUIRED_INPUTS = (
    "benchmarks/m18_validation_matrix.json",
    "reference/validation/v1_release/evidence_index.json",
    "reference/validation/v1_release/evidence_manifest.json",
    "reference/validation/m18_d02_reference_limitation/decision.json",
    "reference/validation/m18_d08_reference_limitation/decision.json",
    "reference/validation/m18_s7_reference_limitation/decision.json",
    "reference/validation/m18_scientific_validation.json",
    "reference/validation/m18_d09/decision.json",
    "gpu_validation_results/m18_s9_physical_gpu_revalidation.json",
    "docs/research/PAPER_EVIDENCE_MAP.md",
    "docs/validation/V1_FINAL_RELEASE_PROVENANCE.md",
    "docs/planning/PYPI_PUBLISHING.md",
    "paper/reproducibility/PAPER_PROTOCOL.md",
)

GENERATED_NOTICE = (
    "<!-- Generated by paper/scripts/generate_core_tables.py. "
    "Do not edit numerical/categorical result cells by hand. -->\n\n"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_text(root: Path, relative: str) -> str:
    path = root / relative
    if not path.is_file():
        raise FileNotFoundError(f"required P2 evidence is missing: {relative}")
    return path.read_text(encoding="utf-8")


def _read_json(root: Path, relative: str) -> dict[str, Any]:
    return json.loads(_read_text(root, relative))


def _require_inputs(root: Path) -> None:
    for relative in REQUIRED_INPUTS:
        path = root / relative
        if not path.is_file():
            raise FileNotFoundError(f"required P2 evidence is missing: {relative}")


def _evidence(items: Iterable[dict[str, Any]], evidence_id: str) -> dict[str, Any]:
    matches = [item for item in items if item.get("id") == evidence_id]
    if len(matches) != 1:
        raise KeyError(f"expected one evidence item {evidence_id!r}, found {len(matches)}")
    return matches[0]


def _match(text: str, pattern: str, label: str, *, flags: int = 0) -> str:
    match = re.search(pattern, text, flags)
    if match is None:
        raise ValueError(f"required provenance field not found: {label}")
    return match.group(1)


def _md(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        value = format(value, ".17g")
    text = str(value).replace("|", "\\|").replace("\n", "<br>")
    return text


def _table(title: str, headers: list[str], rows: list[list[Any]], note: str | None = None) -> str:
    lines = [GENERATED_NOTICE.rstrip(), f"# {title}", ""]
    if note:
        lines.extend([note, ""])
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(f"row length {len(row)} does not match {len(headers)} headers")
        lines.append("| " + " | ".join(_md(cell) for cell in row) + " |")
    lines.append("")
    return "\n".join(lines)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _parse_protocol(protocol_text: str) -> dict[str, str]:
    return {
        "id": _match(protocol_text, r"Protocol ID:\s*\*\*`([^`]+)`\*\*", "paper protocol ID"),
        "status": _match(protocol_text, r"Status:\s*\*\*([^*]+)\*\*", "paper protocol status").strip(),
        "product_tag": _match(
            protocol_text,
            r"HGFX product source:\s*\*\*`([^`]+)`\s*@",
            "HGFX product tag",
        ),
        "product_sha": _match(
            protocol_text,
            r"HGFX product source:\s*\*\*`[^`]+`\s*@\s*`([0-9a-f]{40})`\*\*",
            "HGFX product SHA",
        ),
        "matlab_version": _match(
            protocol_text,
            r"MATLAB compatibility oracle:\s*\*\*HGF Toolbox\s+([^\s]+)\s+@",
            "MATLAB HGF version",
        ),
        "matlab_sha": _match(
            protocol_text,
            r"MATLAB compatibility oracle:\s*\*\*HGF Toolbox\s+[^\s]+\s+@\s*`([0-9a-f]{40})`",
            "MATLAB reference SHA",
        ),
    }


def _parse_demo_rows(evidence_map: str) -> list[dict[str, str]]:
    patterns = (
        (
            "Classic HGF vs eHGF official demo",
            r"Official classic-HGF/eHGF demo behavior is reproduced\s*\|\s*READY\s*\|\s*`([^`]+)`; run `([0-9]+)`; artifact `([0-9]+)`",
            "classic HGF/eHGF demo evidence",
            "Classic HGF fails in the frozen regime while eHGF succeeds; HGFX reproduces the reference workflow behavior.",
        ),
        (
            "uHGF to uHGF-AR(1) official demo",
            r"Official uHGF→AR\(1\) demo workflow is reproduced\s*\|\s*READY\s*\|\s*`([^`]+)`; run `([0-9]+)`; artifact `([0-9]+)`",
            "uHGF/AR1 demo evidence",
            "The frozen uHGF to uHGF-AR(1) workflow is reproduced on the validated official-demo scope.",
        ),
    )
    result: list[dict[str, str]] = []
    for name, pattern, label, behavior in patterns:
        match = re.search(pattern, evidence_map)
        if match is None:
            raise ValueError(f"required provenance field not found: {label}")
        classification, run, artifact = match.groups()
        result.append(
            {
                "workflow": name,
                "behavior": behavior,
                "classification": classification,
                "run": run,
                "artifact": artifact,
            }
        )
    return result


def _parse_final_release(text: str) -> dict[str, str]:
    return {
        "source_sha": _match(
            text,
            r"The immutable v1\.0\.0 release source is `([0-9a-f]{40})`",
            "final v1 source SHA",
        ),
        "main_regression_run": _match(text, r"Main validation run: `([0-9]+)`", "main regression run"),
        "release_id": _match(text, r"GitHub Release ID: `([0-9]+)`", "GitHub Release ID"),
        "published": _match(text, r"Published: `([^`]+)`", "GitHub release publication timestamp"),
    }


def _parse_pypi(text: str) -> dict[str, str]:
    publish = _match(
        text,
        r"PyPI Release\s*\nRun ID:\s*([0-9]+)",
        "PyPI publication workflow run",
        flags=re.MULTILINE,
    )
    verify = _match(
        text,
        r"Verify PyPI Distribution\s*\nRun ID:\s*([0-9]+)",
        "PyPI public-index verification run",
        flags=re.MULTILINE,
    )
    return {"publish_run": publish, "verify_run": verify}


def generate_tables(root: Path | str, output_dir: Path | str) -> dict[str, Any]:
    root = Path(root).resolve()
    output_dir = Path(output_dir).resolve()
    _require_inputs(root)
    output_dir.mkdir(parents=True, exist_ok=True)

    matrix = _read_json(root, "benchmarks/m18_validation_matrix.json")
    release_index = _read_json(root, "reference/validation/v1_release/evidence_index.json")
    release_manifest = _read_json(root, "reference/validation/v1_release/evidence_manifest.json")
    d02 = _read_json(root, "reference/validation/m18_d02_reference_limitation/decision.json")
    d08 = _read_json(root, "reference/validation/m18_d08_reference_limitation/decision.json")
    s7 = _read_json(root, "reference/validation/m18_s7_reference_limitation/decision.json")
    historical_m18 = _read_json(root, "reference/validation/m18_scientific_validation.json")
    d09 = _read_json(root, "reference/validation/m18_d09/decision.json")
    gpu = _read_json(root, "gpu_validation_results/m18_s9_physical_gpu_revalidation.json")
    evidence_map = _read_text(root, "docs/research/PAPER_EVIDENCE_MAP.md")
    final_release_text = _read_text(root, "docs/validation/V1_FINAL_RELEASE_PROVENANCE.md")
    pypi_text = _read_text(root, "docs/planning/PYPI_PUBLISHING.md")
    protocol_text = _read_text(root, "paper/reproducibility/PAPER_PROTOCOL.md")

    protocol = _parse_protocol(protocol_text)
    final_release = _parse_final_release(final_release_text)
    pypi = _parse_pypi(pypi_text)
    demo_rows = _parse_demo_rows(evidence_map)

    if final_release["source_sha"] != protocol["product_sha"]:
        raise ValueError("paper protocol HGFX source does not match final v1 release provenance")
    if matrix["reference"]["commit"] != protocol["matlab_sha"]:
        raise ValueError("M18 validation matrix reference does not match paper protocol oracle")

    indexed = release_index["evidence"]
    external = release_manifest["external_evidence"]
    m0_m17 = _evidence(indexed, "M0-M17")
    m18_hist_index = _evidence(indexed, "M18_HISTORICAL_SCIENTIFIC")
    s9_gpu_index = _evidence(indexed, "S9_PHYSICAL_GPU")
    m19 = _evidence(external, "M19_EVIDENCE_FREEZE")

    coverage_rows: list[list[Any]] = []
    for workflow in matrix["reference_workflows"]:
        coverage_rows.append(
            [
                workflow["id"],
                workflow["perceptual_model"],
                workflow["observation_model"],
                workflow["required"],
                workflow["recovery"],
                m0_m17["classification"],
                "benchmarks/m18_validation_matrix.json; reference/validation/v1_release/evidence_index.json#M0-M17",
            ]
        )
    _write(
        output_dir / "model_workflow_coverage.md",
        _table(
            "Model and workflow coverage",
            ["Workflow", "Perceptual model", "Observation model", "Required", "Recovery scope", "v1 classification", "Evidence"],
            coverage_rows,
            "Coverage is reported only in the documented v1 scopes; the aggregate classification must not be generalized beyond the frozen inventory.",
        ),
    )

    _write(
        output_dir / "official_matlab_demo_parity.md",
        _table(
            "Official MATLAB demo parity",
            ["Workflow", "Validated behavior", "Classification", "Workflow run", "Artifact", "Evidence"],
            [
                [
                    row["workflow"],
                    row["behavior"],
                    row["classification"],
                    row["run"],
                    row["artifact"],
                    "docs/research/PAPER_EVIDENCE_MAP.md; docs/user/MATLAB_DEMOS.md",
                ]
                for row in demo_rows
            ],
            "These are workflow-equivalence results under the frozen official-demo scope, not universal claims for every dataset or optimizer trajectory.",
        ),
    )

    d10d11 = _evidence(external, "D10_D11_ANALYSIS")
    d12 = _evidence(external, "D12_BPA")
    fitting_rows = [
        [
            "D02 exact fit",
            d02["direct_gate_status"],
            d02["release_classification"],
            d02["direct_evidence"]["classification"],
            "Direct failure remains preserved; release disposition is exact-scope only.",
            "reference/validation/m18_d02_reference_limitation/decision.json",
        ],
        [
            "D08 failed-seed exact fit",
            d08["direct_gate_status"],
            d08["release_classification"],
            d08["optimizer_localization_evidence"]["classification"],
            f"Prospective holdout status: {d08['prospective_level2_holdout_status']}.",
            "reference/validation/m18_d08_reference_limitation/decision.json",
        ],
        [
            "D09 sampleModel",
            d09["status"],
            d09["classification"],
            d09["protocol"],
            "Both frozen paired sampleModel cases passed under the recorded protocol.",
            "reference/validation/m18_d09/decision.json",
        ],
        [
            "D10/D11 analysis/statistics surfaces",
            d10d11["classification"],
            d10d11["classification"],
            "release-frozen workflow evidence",
            f"Workflow run {d10d11.get('workflow_run', 'recorded in frozen manifest')}.",
            "reference/validation/v1_release/evidence_manifest.json#D10_D11_ANALYSIS",
        ],
        [
            "D12 BPA",
            d12["classification"],
            d12["classification"],
            "release-frozen workflow evidence",
            f"Workflow run {d12.get('workflow_run', 'recorded in frozen manifest')}.",
            "reference/validation/v1_release/evidence_manifest.json#D12_BPA",
        ],
    ]
    _write(
        output_dir / "fitting_statistics_classification.md",
        _table(
            "Fitting and statistics classifications",
            ["Case", "Direct/scientific status", "Release classification", "Mechanism/protocol", "Scope note", "Evidence"],
            fitting_rows,
            "`REFERENCE_LIMITATION_MATCH` is deliberately distinct from direct/scientific PASS. D02 and D08 direct failures remain visible.",
        ),
    )

    observed = historical_m18["gate"]["observed"]
    criteria = historical_m18["gate"]["criteria"]
    recovery_rows: list[list[Any]] = [
        [
            "M18 historical scientific gate",
            m18_hist_index["classification"],
            f"min convergence={observed['minimum_parameter_convergence_rate']}; min median correlation={observed['minimum_parameter_median_correlation']}; max median standardized RMSE={observed['maximum_parameter_median_standardized_rmse']}; model-recovery balanced accuracy={observed['model_recovery_balanced_accuracy']}",
            f"criteria: convergence>={criteria['parameter_convergence_rate_min']}; correlation>={criteria['parameter_median_correlation_min']}; standardized RMSE<={criteria['parameter_median_standardized_rmse_max']}; balanced accuracy>={criteria['model_recovery_balanced_accuracy_min']}",
            "reference/validation/m18_scientific_validation.json; reference/validation/v1_release/evidence_index.json#M18_HISTORICAL_SCIENTIFIC",
        ]
    ]
    for model in ("hgf_binary", "ehgf_binary", "uhgf_binary"):
        record = s7["parameter_recovery"][model]
        matlab = record["matlab"]
        hgfx = record["hgfx"]
        recovery_rows.append(
            [
                f"S7 parameter recovery — {model}",
                record["classification"],
                f"MATLAB: convergence={matlab['convergence_rate']}, median correlation={matlab['median_correlation']}, median standardized RMSE={matlab['median_standardized_rmse']}; HGFX: convergence={hgfx['convergence_rate']}, median correlation={hgfx['median_correlation']}, median standardized RMSE={hgfx['median_standardized_rmse']}",
                "shared failed criteria: " + ", ".join(record["shared_failed_criteria"]),
                "reference/validation/m18_s7_reference_limitation/decision.json",
            ]
        )
    model_recovery = s7["model_recovery"]
    recovery_rows.append(
        [
            "S7 paired model selection",
            model_recovery["classification"],
            f"BIC winner agreement={model_recovery['winner_matches']}/{model_recovery['total_cases']}; MATLAB balanced accuracy={model_recovery['matlab_balanced_accuracy']}; HGFX balanced accuracy={model_recovery['hgfx_balanced_accuracy']}",
            "No winner mismatches in the frozen paired grid.",
            "reference/validation/m18_s7_reference_limitation/decision.json",
        ]
    )
    _write(
        output_dir / "recovery_model_selection.md",
        _table(
            "Recovery and model-selection evidence",
            ["Evidence scope", "Classification", "Observed summary", "Interpretation/criterion", "Evidence"],
            recovery_rows,
            "Parameter recovery and model selection are reported separately. Historical M18 FAIL is not converted into PASS by the later paired model-selection result.",
        ),
    )

    s9_cpu = _evidence(external, "S9_CPU_BACKEND")
    gpu_cases = gpu["physical_gpu"]["cases"]
    max_gpu_gap = max(float(case["final_objective_gap"]) for case in gpu_cases)
    gpu_threshold = gpu["criteria"]["jax_cpu_vs_physical_gpu_final_objective_gap_max"]
    hardware = s9_gpu_index.get("hardware")
    if not hardware:
        raise ValueError("S9 physical-GPU hardware is missing from the frozen evidence index")
    backend_rows = [
        [
            "S9 CPU/backend",
            s9_cpu["classification"],
            "ubuntu-24.04",
            f"run={s9_cpu.get('workflow_run')}; job={s9_cpu.get('job')}; artifact={s9_cpu.get('artifact')}",
            "CPU/backend numerical-equivalence evidence in the frozen scope.",
            "reference/validation/v1_release/evidence_manifest.json#S9_CPU_BACKEND",
        ],
        [
            "S9 physical NVIDIA GPU",
            gpu["physical_gpu"]["classification"],
            hardware,
            f"Python {gpu['environment']['python']}; JAX {gpu['environment']['jax']}; max final-objective gap={max_gpu_gap}; criterion={gpu_threshold}",
            "correctness/applicability only; does not establish speed or scaling; hosted/shared environment recorded in evidence.",
            "gpu_validation_results/m18_s9_physical_gpu_revalidation.json; reference/validation/v1_release/evidence_index.json#S9_PHYSICAL_GPU",
        ],
    ]
    _write(
        output_dir / "backend_gpu_applicability.md",
        _table(
            "Backend and physical-GPU applicability",
            ["Scope", "Classification", "Environment/hardware", "Recorded result", "Claim boundary", "Evidence"],
            backend_rows,
            "The physical-GPU row is an applicability/correctness result. Paper protocol 1 does not activate a general performance or scaling claim.",
        ),
    )

    release_rows = [
        [
            "MATLAB compatibility oracle",
            f"HGF Toolbox {protocol['matlab_version']}",
            protocol["matlab_sha"],
            "paper/reproducibility/PAPER_PROTOCOL.md; benchmarks/m18_validation_matrix.json",
        ],
        [
            "HGFX immutable v1.0.0 source",
            protocol["product_tag"],
            final_release["source_sha"],
            "docs/validation/V1_FINAL_RELEASE_PROVENANCE.md; paper/reproducibility/PAPER_PROTOCOL.md",
        ],
        [
            "M19 release-evidence freeze",
            m19["classification"],
            f"manifest_status={m19.get('manifest_status')}; failures={m19.get('failures')}",
            "reference/validation/v1_release/evidence_manifest.json#M19_EVIDENCE_FREEZE",
        ],
        [
            "Final main cross-platform regression",
            "PASS (Ubuntu + Windows)",
            f"run={final_release['main_regression_run']}",
            "docs/validation/V1_FINAL_RELEASE_PROVENANCE.md",
        ],
        [
            "GitHub Release",
            f"release_id={final_release['release_id']}",
            f"published={final_release['published']}",
            "docs/validation/V1_FINAL_RELEASE_PROVENANCE.md",
        ],
        [
            "Public PyPI distribution",
            "hgfx==1.0.0",
            f"publish_run={pypi['publish_run']}; public_index_verify_run={pypi['verify_run']}",
            "docs/planning/PYPI_PUBLISHING.md",
        ],
        [
            "Paper execution protocol",
            protocol["id"],
            protocol["status"],
            "paper/reproducibility/PAPER_PROTOCOL.md",
        ],
    ]
    _write(
        output_dir / "release_reproducibility_provenance.md",
        _table(
            "Release and reproducibility provenance",
            ["Record", "Identity/status", "Pinned provenance", "Evidence"],
            release_rows,
            "This table records release/protocol provenance. It does not strengthen or reclassify the frozen scientific validation outcomes.",
        ),
    )

    input_hashes = [
        {"path": relative, "sha256": _sha256(root / relative)} for relative in REQUIRED_INPUTS
    ]
    output_hashes = [
        {"path": name, "sha256": _sha256(output_dir / name)} for name in TABLE_NAMES
    ]
    generator_path = Path(__file__).resolve()
    manifest: dict[str, Any] = {
        "schema_version": 1,
        "protocol_id": protocol["id"],
        "hgfx_product": {"tag": protocol["product_tag"], "source_sha": protocol["product_sha"]},
        "matlab_reference": {"version": protocol["matlab_version"], "source_sha": protocol["matlab_sha"]},
        "generator": {
            "path": "paper/scripts/generate_core_tables.py",
            "sha256": _sha256(generator_path),
        },
        "inputs": input_hashes,
        "outputs": list(TABLE_NAMES),
        "output_hashes": output_hashes,
        "integrity": {
            "historical_m18_fail_visible": m18_hist_index["classification"] == "FAIL_PRESERVED",
            "d02_direct_fail_visible": d02["direct_gate_status"] == "FAIL_PRESERVED",
            "d08_direct_fail_visible": d08["direct_gate_status"] == "FAIL_PRESERVED",
            "reference_limitation_visible": (
                d02["release_classification"] == "REFERENCE_LIMITATION_MATCH"
                and d08["release_classification"] == "REFERENCE_LIMITATION_MATCH"
                and s7["decision"] == "REFERENCE_LIMITATION_MATCH"
            ),
            "performance_claim_activated": False,
        },
    }
    if not all(
        manifest["integrity"][key]
        for key in (
            "historical_m18_fail_visible",
            "d02_direct_fail_visible",
            "d08_direct_fail_visible",
            "reference_limitation_visible",
        )
    ):
        raise ValueError("P2 integrity gate failed: negative/reference-limitation evidence was not preserved")

    (output_dir / "core_tables_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root (default: inferred from this script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tables",
        help="output directory (default: paper/tables)",
    )
    args = parser.parse_args()
    manifest = generate_tables(args.root, args.output)
    print(
        f"Generated {len(manifest['outputs'])} P2 tables under {args.output} "
        f"using protocol {manifest['protocol_id']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
