from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

PROTOCOL_ID = "hgfx-paper-protocol-1"
HGFX_RELEASE_VERSION = "1.0.0"
HGFX_RELEASE_COMMIT = "4dd8fbd8239d05f2c7932a9a9b3b7795f0a9ab27"
REQUIRED_INPUTS = (
    "reference/validation/v1_release/evidence_manifest.json",
    "reference/validation/v1_release/evidence_index.json",
    "reference/validation/m18_d02_reference_limitation/decision.json",
    "reference/validation/m18_d08_reference_limitation/decision.json",
    "reference/validation/m18_s7_reference_limitation/decision.json",
    "paper/reproducibility/p3_m18c2_aggregate_35272347167.json",
)
TABLE_ORDER = (
    "model_workflow_coverage.md",
    "matlab_demo_parity.md",
    "fitting_statistics_classification.md",
    "recovery_model_selection.md",
    "backend_gpu_applicability.md",
    "release_reproducibility_provenance.md",
    "p3_horizon_summary.md",
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _evidence_map(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {item["id"]: item for item in manifest["external_evidence"]}


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        return format(value, ".12g")
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _evidence_label(item: dict[str, Any], fallback: str) -> str:
    bits = [fallback]
    if item.get("workflow_run"):
        bits.append(f"run {item['workflow_run']}")
    if item.get("artifact"):
        bits.append(f"artifact {item['artifact']}")
    if item.get("source") and item["source"] != fallback:
        bits.append(str(item["source"]))
    return "; ".join(bits)


def _table(title: str, headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        f"# {title}",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(cell).replace("|", "\\|") for cell in row) + " |")
    lines.extend(
        [
            "",
            f"Generated by `paper/scripts/generate_p2_tables.py` under `{PROTOCOL_ID}`.",
            "",
        ]
    )
    return "\n".join(lines)


def build_outputs(repo_root: Path) -> tuple[dict[str, str], dict[str, Any]]:
    root = Path(repo_root)
    paths = [root / rel for rel in REQUIRED_INPUTS]
    missing = [str(path.relative_to(root)) for path in paths if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing required P2 evidence inputs: " + ", ".join(missing))

    manifest = _load_json(paths[0])
    evidence_index = _load_json(paths[1])
    d02 = _load_json(paths[2])
    d08 = _load_json(paths[3])
    s7 = _load_json(paths[4])
    p3 = _load_json(paths[5])
    evidence = _evidence_map(manifest)
    index_evidence = {item["id"]: item for item in evidence_index["evidence"]}
    matlab_ref = manifest["frozen_matlab_reference"]
    if matlab_ref != d02["reference_commit"] or matlab_ref != d08["reference_commit"]:
        raise ValueError("Frozen MATLAB reference mismatch across P2 inputs")

    coverage_ids = ["M0-M17", "D04_UHGF_AR1", "D09_SAMPLEMODEL", "D10_D11_ANALYSIS", "D12_BPA"]
    coverage_labels = {
        "M0-M17": "Core model/API compatibility milestones",
        "D04_UHGF_AR1": "uHGF -> AR(1) official workflow",
        "D09_SAMPLEMODEL": "sampleModel / prior-predictive workflow",
        "D10_D11_ANALYSIS": "Corr/Sigma + residual analysis surfaces",
        "D12_BPA": "Bayesian parameter averaging",
    }
    coverage_rows = []
    for item_id in coverage_ids:
        item = evidence[item_id]
        coverage_rows.append(
            [
                coverage_labels[item_id],
                item["classification"],
                _evidence_label(
                    item,
                    item.get("source", "reference/validation/v1_release/evidence_manifest.json"),
                ),
            ]
        )

    demo_rows = [
        [
            d02["case_id"],
            d02["direct_gate_status"],
            d02["release_classification"],
            "reference/validation/m18_d02_reference_limitation/decision.json; "
            f"run {d02['direct_evidence']['current_product_official_run']}",
        ],
        [
            "D04_UHGF_AR1",
            evidence["D04_UHGF_AR1"]["classification"],
            evidence["D04_UHGF_AR1"]["classification"],
            _evidence_label(
                evidence["D04_UHGF_AR1"],
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
        [
            d08["case_id"],
            d08["direct_gate_status"],
            d08["release_classification"],
            "reference/validation/m18_d08_reference_limitation/decision.json; "
            f"run {d08['prospective_holdout_evidence']['run']}",
        ],
        [
            "D09_SAMPLEMODEL",
            "PASS",
            "PASS",
            _evidence_label(
                evidence["D09_SAMPLEMODEL"],
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
        [
            "D10_D11_ANALYSIS",
            "PASS",
            "PASS",
            _evidence_label(
                evidence["D10_D11_ANALYSIS"],
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
        [
            "D12_BPA",
            "PASS",
            "PASS",
            _evidence_label(
                evidence["D12_BPA"],
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
    ]

    fitting_rows = [
        [
            "Historical M18 scientific experiment",
            evidence["M18_HISTORICAL_SCIENTIFIC"]["classification"],
            "Historical failure remains preserved",
            _evidence_label(
                evidence["M18_HISTORICAL_SCIENTIFIC"],
                evidence["M18_HISTORICAL_SCIENTIFIC"].get(
                    "source", "reference/validation/v1_release/evidence_manifest.json"
                ),
            ),
        ],
        [
            "D02 fitting",
            d02["direct_evidence"]["classification"],
            d02["release_classification"],
            "reference/validation/m18_d02_reference_limitation/decision.json",
        ],
        [
            "D08 fitting holdout",
            d08["prospective_holdout_evidence"]["seed_314159265"],
            d08["release_classification"],
            "reference/validation/m18_d08_reference_limitation/decision.json",
        ],
        [
            "S7 parameter recovery",
            "scientific_pass=false",
            s7["decision"],
            "reference/validation/m18_s7_reference_limitation/decision.json",
        ],
        [
            "S7 model selection",
            s7["model_recovery"]["classification"],
            f"{s7['model_recovery']['winner_matches']}/{s7['model_recovery']['total_cases']} "
            "winners match",
            "reference/validation/m18_s7_reference_limitation/decision.json",
        ],
    ]

    recovery_rows = []
    for model in ("hgf_binary", "ehgf_binary", "uhgf_binary"):
        item = s7["parameter_recovery"][model]
        recovery_rows.append(
            [
                model,
                item["classification"],
                _fmt(item["matlab"]["convergence_rate"]),
                _fmt(item["hgfx"]["convergence_rate"]),
                _fmt(item["matlab"]["median_correlation"]),
                _fmt(item["hgfx"]["median_correlation"]),
                _fmt(item["matlab"]["median_standardized_rmse"]),
                _fmt(item["hgfx"]["median_standardized_rmse"]),
                ", ".join(item["shared_failed_criteria"]),
                "reference/validation/m18_s7_reference_limitation/decision.json",
            ]
        )
    mr = s7["model_recovery"]
    recovery_rows.append(
        [
            "paired model selection",
            mr["classification"],
            "-",
            "-",
            "-",
            "-",
            _fmt(mr["matlab_balanced_accuracy"]),
            _fmt(mr["hgfx_balanced_accuracy"]),
            f"{mr['winner_matches']}/{mr['total_cases']} winners match; "
            f"mismatches={len(mr['mismatched_cases'])}",
            "reference/validation/m18_s7_reference_limitation/decision.json",
        ]
    )

    cpu = evidence["S9_CPU_BACKEND"]
    gpu_manifest = evidence["S9_PHYSICAL_GPU"]
    gpu_index = index_evidence["S9_PHYSICAL_GPU"]
    backend_rows = [
        [
            "Compatibility vs JAX CPU",
            cpu["classification"],
            "CPU",
            "objective/backend equivalence",
            _evidence_label(
                cpu,
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
        [
            "Physical NVIDIA GPU",
            gpu_manifest["classification"],
            gpu_manifest["hardware"],
            f"jax_backend={gpu_manifest['jax_backend']}; "
            f"max objective gap={_fmt(gpu_index['max_objective_gap'])}; "
            f"criterion={_fmt(gpu_index['criterion'])}",
            _evidence_label(
                gpu_manifest,
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
    ]

    freeze = evidence["M19_EVIDENCE_FREEZE"]
    provenance_rows = [
        [
            "Paper protocol",
            PROTOCOL_ID,
            "frozen before P2 execution",
            "paper/reproducibility/PAPER_PROTOCOL.md",
        ],
        [
            "HGFX release",
            HGFX_RELEASE_VERSION,
            HGFX_RELEASE_COMMIT,
            "v1.0.0 tag + frozen paper protocol",
        ],
        [
            "MATLAB oracle",
            "HGF Toolbox 8.2.0",
            matlab_ref,
            "reference/validation/v1_release/evidence_manifest.json",
        ],
        [
            "M19 release evidence",
            freeze["classification"],
            f"status={freeze['manifest_status']}; failures={freeze['failures']}",
            _evidence_label(
                freeze,
                "reference/validation/v1_release/evidence_manifest.json",
            ),
        ],
        [
            "Historical failures rewritten",
            manifest["integrity"]["historical_failures_rewritten"],
            "must remain false",
            "reference/validation/v1_release/evidence_manifest.json",
        ],
        [
            "Thresholds changed for freeze",
            manifest["integrity"]["thresholds_changed_for_freeze"],
            "must remain false",
            "reference/validation/v1_release/evidence_manifest.json",
        ],
        [
            "Seeds/datasets changed for freeze",
            manifest["integrity"]["seeds_or_datasets_changed_for_freeze"],
            "must remain false",
            "reference/validation/v1_release/evidence_manifest.json",
        ],
        [
            "Validation grid changed for freeze",
            manifest["integrity"]["validation_grid_changed_for_freeze"],
            "must remain false",
            "reference/validation/v1_release/evidence_manifest.json",
        ],
    ]

    p3_lines = [
        "# P3 trial-horizon summary (diagnostic)",
        "",
        f"Official overall class: \`{p3['overall_classification']}\` (\`gate_pass={str(p3['gate_pass']).lower()}\`). Run \`35272347167\`.",
        "Do not treat diagnostic PASS rows as a paper-1 identifiability result.",
        "",
        "| Model | T | MATLAB/HGFX conv | median r MATLAB/HGFX | median sRMSE MATLAB/HGFX | scientific_pass |",
        "|---|---:|---|---|---|---|",
    ]
    for model in ("hgf_binary", "ehgf_binary", "uhgf_binary"):
        horizons = p3["parameter_recovery"][model]["horizons"]
        for horizon in (128, 256, 512, 1024):
            record = horizons[str(horizon)]
            matlab = record["matlab"]
            hgfx = record["hgfx"]
            if not (matlab.get("complete", False) and hgfx.get("complete", False)):
                p3_lines.append(
                    f"| {model} | {horizon} | — | — | — | invalid trajectories retained |"
                )
                continue
            status = "PASS (diagnostic)" if matlab["scientific_pass"] and hgfx["scientific_pass"] else "FAIL"
            p3_lines.append(
                f"| {model} | {horizon} | "
                f"{matlab['convergence_rate']:.3f} / {hgfx['convergence_rate']:.3f} | "
                f"{matlab['median_correlation']:.3f} / {hgfx['median_correlation']:.3f} | "
                f"{matlab['median_standardized_rmse']:.3f} / {hgfx['median_standardized_rmse']:.3f} | "
                f"{status} |"
            )
    p3_lines.extend(
        [
            "",
            f"Generated by \`paper/scripts/generate_p2_tables.py\` under \`{PROTOCOL_ID}\`.",
            "",
        ]
    )
    p3_horizon_summary = "\n".join(p3_lines)

    tables = {
        "model_workflow_coverage.md": _table(
            "P2 Model and Workflow Coverage",
            ["Surface", "Classification", "Evidence"],
            coverage_rows,
        ),
        "matlab_demo_parity.md": _table(
            "P2 Official MATLAB Workflow / Demo Parity",
            ["Case", "Direct result", "Paper classification", "Evidence"],
            demo_rows,
        ),
        "fitting_statistics_classification.md": _table(
            "P2 Fitting and Statistical Classification",
            ["Surface", "Direct/scientific result", "Release/paper disposition", "Evidence"],
            fitting_rows,
        ),
        "recovery_model_selection.md": _table(
            "P2 Recovery and Model Selection",
            [
                "Model/surface",
                "Classification",
                "MATLAB convergence",
                "HGFX convergence",
                "MATLAB median corr",
                "HGFX median corr",
                "MATLAB metric",
                "HGFX metric",
                "Failed criteria / model-selection result",
                "Evidence",
            ],
            recovery_rows,
        ),
        "backend_gpu_applicability.md": _table(
            "P2 Backend and GPU Applicability",
            ["Surface", "Classification", "Hardware/backend", "Result", "Evidence"],
            backend_rows,
        ),
        "release_reproducibility_provenance.md": _table(
            "P2 Release and Reproducibility Provenance",
            ["Item", "Status/value", "Detail", "Evidence"],
            provenance_rows,
        ),
        "p3_horizon_summary.md": p3_horizon_summary,
    }

    output_hashes = {
        name: hashlib.sha256(text.encode("utf-8")).hexdigest()
        for name, text in tables.items()
    }
    output_manifest = {
        "schema_version": 1,
        "protocol_id": PROTOCOL_ID,
        "hgfx_release_commit": HGFX_RELEASE_COMMIT,
        "matlab_reference_commit": matlab_ref,
        "inputs": [{"path": rel, "sha256": _sha256(root / rel)} for rel in REQUIRED_INPUTS],
        "outputs": output_hashes,
    }
    return tables, output_manifest


def write_outputs(repo_root: Path) -> dict[str, Any]:
    tables, manifest = build_outputs(repo_root)
    out_dir = Path(repo_root) / "paper" / "tables"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in tables.items():
        (out_dir / name).write_text(text, encoding="utf-8")
    (out_dir / "p2_tables_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate P2 paper tables from frozen v1 evidence")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    manifest = write_outputs(args.repo_root)
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
