from __future__ import annotations
import argparse,csv,hashlib,io,json
from pathlib import Path
from typing import Any
R=Path(__file__).resolve().parents[2]; S=R/'paper/reproducibility/core_tables_spec.json'; D=R/'paper/tables'; M=D/'core_tables_manifest.json'
IDS={'model_workflow_coverage','official_demo_parity','fitting_statistics_classification','recovery_model_selection','backend_gpu_applicability','release_reproducibility_provenance'}
def h(b:bytes)->str:return hashlib.sha256(b).hexdigest()
def hf(p:Path)->str:return h(p.read_bytes())
def j(p:Path)->Any:
 if not p.is_file():raise FileNotFoundError(f'Required evidence file is missing: {p.relative_to(R)}')
 return json.loads(p.read_text(encoding='utf-8'))
def d(x:Any)->str:
 if x is None:return '—'
 if isinstance(x,bool):return str(x).lower()
 if isinstance(x,float):return repr(x)
 if isinstance(x,list):return '[]' if not x else ', '.join(map(d,x))
 return str(x)
def sources(spec):
 out={}; prov={}
 for a,m in spec['sources'].items():
  p=R/m['path']; x=j(p); actual=hf(p)
  if actual!=m['sha256']:raise RuntimeError(f"Frozen evidence hash mismatch for {m['path']}: expected {m['sha256']}, got {actual}")
  out[a]=x; prov[a]={'path':m['path'],'sha256':actual}
 return out,prov
def md(title,cols,rows):
 esc=lambda x:x.replace('|','\\|').replace('\n',' ')
 z=['<!-- Generated by paper/scripts/generate_core_tables.py; do not edit manually. -->',f'# {title}','','| '+' | '.join(map(esc,cols))+' |','| '+' | '.join('---' for _ in cols)+' |']
 z+=['| '+' | '.join(map(esc,r))+' |' for r in rows];return '\n'.join(z)+'\n'
def cv(cols,rows):
 q=io.StringIO(newline='');w=csv.writer(q,lineterminator='\n');w.writerow(cols);w.writerows(rows);return q.getvalue()
def coverage(x):
 c=['Workflow','Perceptual model','Observation model','Required','Recovery','Notes','Evidence'];r=[]
 for z in x['snapshot']['model_workflows']:r.append([d(z[k]) for k in ('id','perceptual_model','observation_model','required','recovery','notes','evidence')])
 return c,r
def demos(x):
 c=['Case','Classification','MATLAB primary success','HGFX primary success','MATLAB alternate success','HGFX alternate success','Mismatches','Workflow/artifact','Evidence'];a=x['snapshot']['demo_artifacts'];p=x['demo_model_selection'];u=x['demo_uhgf_ar1']
 r=[[p['case_id'],p['classification'],d(p['matlab']['hgf_binary']['success']),d(p['hgfx']['hgf_binary']['success']),d(p['matlab']['ehgf_binary']['success']),d(p['hgfx']['ehgf_binary']['success']),d(p['mismatches']),f"run {a['model_selection']['workflow_run']}; artifact {a['model_selection']['artifact_id']}",a['model_selection']['classification_file']],[u['case_id'],u['classification'],d(u['matlab']['uhgf_binary']['success']),d(u['hgfx']['uhgf_binary']['success']),d(u['matlab']['uhgf_ar1_binary']['success']),d(u['hgfx']['uhgf_ar1_binary']['success']),d(u['mismatches']),f"run {a['uhgf_ar1']['workflow_run']}; artifact {a['uhgf_ar1']['artifact_id']}",a['uhgf_ar1']['classification_file']]];return c,r
def fitting(x):
 c=['Case','Surface','Direct/prospective status','Detailed classification','Release classification','Workflow/artifact','Evidence'];a=x['d02'];b=x['d08'];s=x['snapshot'];r=[[a['case_id'],'official eHGF + unitsq_sgm fit',a['direct_gate_status'],a['direct_evidence']['classification'],a['release_classification'],f"run {a['direct_evidence']['current_product_official_run']}; artifact {a['direct_evidence']['current_product_artifact']}",'reference/validation/m18_d02_reference_limitation/decision.json'],[b['case_id'],'prospective uHGF + gaussian_obs holdout fit',b['prospective_level2_holdout_status'],b['prospective_holdout_evidence']['seed_314159265'],b['release_classification'],f"run {b['prospective_holdout_evidence']['run']}; artifact {b['prospective_holdout_evidence']['artifact']}",'reference/validation/m18_d08_reference_limitation/decision.json']]
 for z in s['fitting_statistics_passes']:r.append([z['id'],z['surface'],z['classification'],z['classification'],z['classification'],f"run {z['workflow_run']}; artifact {z['artifact_id']}",z['evidence']])
 return c,r
def recovery(x):
 c=['Item','Classification','MATLAB convergence','HGFX convergence','MATLAB corr/BA','HGFX corr/BA','MATLAB std RMSE','HGFX std RMSE','Failure/winner summary','Evidence'];q=x['s7'];z=x['snapshot']['historical_m18'];r=[[z['id'],z['classification'],'—','—','—','—','—','—','historical FAIL remains immutable',z['evidence']]]
 for m in ('hgf_binary','ehgf_binary','uhgf_binary'):
  a=q['parameter_recovery'][m];r.append([f'S7 parameter recovery: {m}',a['classification'],d(a['matlab']['convergence_rate']),d(a['hgfx']['convergence_rate']),d(a['matlab']['median_correlation']),d(a['hgfx']['median_correlation']),d(a['matlab']['median_standardized_rmse']),d(a['hgfx']['median_standardized_rmse']),d(a['shared_failed_criteria']),'reference/validation/m18_s7_reference_limitation/decision.json'])
 a=q['model_recovery'];r.append(['S7 model selection',a['classification'],'—','—',d(a['matlab_balanced_accuracy']),d(a['hgfx_balanced_accuracy']),'—','—',f"{a['winner_matches']}/{a['total_cases']} BIC winners match",'reference/validation/m18_s7_reference_limitation/decision.json']);return c,r
def backend(x):
 c=['Evidence item','Classification','Hardware/backend','Environment','Objective gap','Criterion','Workflow/source','Evidence'];a=x['snapshot']['backend']['cpu'];b=x['snapshot']['backend']['physical_gpu'];return c,[[a['id'],a['classification'],'JAX CPU','release validation','—','—',f"run {a['workflow_run']}; artifact {a['artifact_id']}",a['evidence']],[b['id'],b['classification'],f"{b['hardware']}; {b['backend']}",f"Python {b['python']}; JAX/JAXLIB {b['jax']}/{b['jaxlib']}",d(b['max_objective_gap']),d(b['criterion']),f"source commit {b['source_commit']}",b['evidence']]]
def release(x):
 c=['Item','Status','Identifier','Source commit/version','Evidence'];s=x['snapshot'];r=s['release'];v=s['frozen_hgfx_release']['commit'];p=r['pypi'];return c,[['M19 evidence freeze',r['m19']['classification'],f"run {r['m19']['workflow_run']}",v,r['m19']['evidence']],['GitHub release','PUBLISHED',f"{r['github_release']['tag']}; release {r['github_release']['release_id']}",r['github_release']['target_commit'],r['github_release']['api_source']],['Final cross-platform regression',r['final_regression']['conclusion'],f"run {r['final_regression']['workflow_run']}; Ubuntu={r['final_regression']['ubuntu']}; Windows={r['final_regression']['windows']}",r['final_regression']['head_sha'],r['final_regression']['api_source']],['PyPI Trusted Publishing',p['publish_conclusion'],f"run {p['publish_workflow_run']}; {p['package']}=={p['version']}",p['publish_head_sha'],p['evidence']],['Public PyPI install verification',p['verify_conclusion'],f"run {p['verify_workflow_run']}; {p['install_command']}",p['verify_head_sha'],p['evidence']]]
B={'model_workflow_coverage':coverage,'official_demo_parity':demos,'fitting_statistics_classification':fitting,'recovery_model_selection':recovery,'backend_gpu_applicability':backend,'release_reproducibility_provenance':release}
def expected():
 spec=j(S)
 if spec.get('schema_version')!=2:raise ValueError('Unsupported core table spec schema_version')
 x,prov=sources(spec);ids=[z['id'] for z in spec['tables']]
 if len(ids)!=len(set(ids)) or set(ids)!=IDS:raise ValueError('P2 table set mismatch')
 out={}
 for z in spec['tables']:
  c,r=B[z['id']](x);out[z['id']]={'title':z['title'],'markdown':md(z['title'],c,r),'csv':cv(c,r)}
 tables={k:{'title':v['title'],'outputs':{'markdown':{'path':f'paper/tables/{k}.md','sha256':h(v['markdown'].encode())},'csv':{'path':f'paper/tables/{k}.csv','sha256':h(v['csv'].encode())}}} for k,v in out.items()}
 man={'schema_version':1,'status':'GENERATED_FROM_FROZEN_EVIDENCE','generator':{'path':'paper/scripts/generate_core_tables.py','sha256':hf(Path(__file__))},'spec':{'path':'paper/reproducibility/core_tables_spec.json','sha256':hf(S)},'inputs':prov,'tables':tables}
 return out,json.dumps(man,indent=2,sort_keys=True,ensure_ascii=False)+'\n'
def write(out,man):
 D.mkdir(parents=True,exist_ok=True);names={'core_tables_manifest.json'}
 for k,v in out.items():
  for e in ('md','csv'):names.add(f'{k}.{e}')
  (D/f'{k}.md').write_text(v['markdown'],encoding='utf-8',newline='\n');(D/f'{k}.csv').write_text(v['csv'],encoding='utf-8',newline='\n')
 M.write_text(man,encoding='utf-8',newline='\n');extra=sorted(p.name for p in D.iterdir() if p.is_file() and p.name not in names)
 if extra:raise RuntimeError('Unexpected generated table files: '+','.join(extra))
def check(out,man):
 want={M:man};want.update({D/f'{k}.md':v['markdown'] for k,v in out.items()});want.update({D/f'{k}.csv':v['csv'] for k,v in out.items()});miss=[];chg=[]
 for p,t in want.items():
  if not p.is_file():miss.append(str(p.relative_to(R)))
  elif p.read_text(encoding='utf-8')!=t:chg.append(str(p.relative_to(R)))
 actual={p.name for p in D.iterdir() if p.is_file()} if D.is_dir() else set();extra=sorted(actual-{p.name for p in want})
 if miss or chg or extra:raise SystemExit(f'Core paper tables are stale: missing={miss}; changed={chg}; extra={extra}')
 print(f'Core paper table check: PASS ({len(out)} tables)')
def main():
 a=argparse.ArgumentParser();a.add_argument('--check',action='store_true');q=a.parse_args();o,m=expected();check(o,m) if q.check else write(o,m)
if __name__=='__main__':main()
