"""MATLAB compatibility schemas, objective, fitting, and fit statistics."""

from .configs import (
    hgf_ar1_config,
    hgf_binary_config,
    hgf_config,
    unitsq_sgm_config,
    hgf_binary_mab_config,
    hgf_ar1_mab_config,
    hgf_ar1_binary_mab_config,
    ehgf_ar1_binary_mab_config,
    uhgf_ar1_binary_mab_config,
    hgf_jget_config,
    ehgf_jget_config,
    uhgf_jget_config,
    hgf_categorical_config,
    hgf_categorical_norm_config,
    hgf_whatworld_config,
    hgf_whichworld_config,
)
from .fit_statistics import (
    FitStatistics,
    LMEDecomposition,
    finalize_laplace_statistics,
    fit_statistics,
)
from .fitting import (
    CompatibilityFitResult,
    FitProblem,
    fit_hgf_binary_unitsq_compat,
    fit_hgf_binary_unitsq_multistart_compat,
    hgf_binary_unitsq_fit_problem,
)
from .simulation import (
    SimulationResult,
    ehgf_binary_config,
    sample_model,
    sim_model,
    simulate_gaussian_obs,
    simulate_softmax_binary,
    simulate_unitsq_sgm,
    softmax_binary_probability,
    uhgf_binary_config,
    unitsq_sgm_probability,
)
from .objective import (
    ObjectiveResult,
    PriorEvaluation,
    evaluate_objective,
    gaussian_log_prior,
    hgf_binary_unitsq_objective,
)

__all__ = [
    "hgf_binary_config",
    "hgf_ar1_config",
    "hgf_config",
    "hgf_binary_mab_config",
    "hgf_ar1_mab_config",
    "hgf_ar1_binary_mab_config",
    "ehgf_ar1_binary_mab_config",
    "uhgf_ar1_binary_mab_config",
    "hgf_jget_config",
    "ehgf_jget_config",
    "uhgf_jget_config",
    "hgf_categorical_config",
    "hgf_categorical_norm_config",
    "hgf_whatworld_config",
    "hgf_whichworld_config",
    "unitsq_sgm_config",
    "ObjectiveResult",
    "PriorEvaluation",
    "evaluate_objective",
    "gaussian_log_prior",
    "hgf_binary_unitsq_objective",
    "FitProblem",
    "CompatibilityFitResult",
    "hgf_binary_unitsq_fit_problem",
    "fit_hgf_binary_unitsq_compat",
    "fit_hgf_binary_unitsq_multistart_compat",
    "FitStatistics",
    "LMEDecomposition",
    "finalize_laplace_statistics",
    "fit_statistics",
    "SimulationResult",
    "ehgf_binary_config",
    "uhgf_binary_config",
    "sim_model",
    "sample_model",
    "unitsq_sgm_probability",
    "simulate_unitsq_sgm",
    "softmax_binary_probability",
    "simulate_softmax_binary",
    "simulate_gaussian_obs",
]
